### ISSUE TITLE
Suggestion: Bind NO Keys by Default; Read All Keybinds from File

### ISSUE THREAD

**Issue by ghost** [neurocyte/flow#10]
Like River does it, don't enforce any keybindings on the user. There are several reasons to do it like this:
- The many conflicting keybinds of every terminal emulator in existence
- Some people might be coming from Atom or Sublime
- `hjkl` and `ESC` aren't in the same place on a QWERTY keyboard as they were on the keyboard where vi was originally written, which causes real ergonomic and flow problems; and don't even get me started on other layouts
- Any one user will only use a fraction of the available binds, and they'll rebind a few anyway

Of course, this will require a prominent warning against opening Flow without binding a Quit key, as well as perhaps some prewritten binding files.

**Comment by neurocyte** [comment]
All keybinds are already read from a file. Well, one file per mode at least.

I don't see any major advantage to removing the default keybinds. That just adds pointless extra work for the user. I'd rather have Flow Control work out of the box 99% of the time and let the rest tweak their keybindings as needed. I'm pretty sure most people use one of the semi-standard layouts with just a few personal tweaks (if any).

Having keys bound that don't work in your current terminal is minor annoyance and probably more a reason to fix your terminal than change your editor (and break muscle memory).

Atom and/or sublime layouts would be very welcome. And others, many people have already asked about a helix/kak mode.

**Comment by neurocyte** [comment]
I've added the documentation tag because there is no info in the help or readme about adding or modifying keybinds.

I've added the enhancement tag because I'd like to make it much easier to add a whole new custom keybinding mode.

**Comment by neurocyte** [comment]
I'm going to close this because it's sort of the opposite of flow's direction. I try make flow as usable as possible out of the box with no manual configuration needed to get started.
