### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zaeboba** [neurocyte/flow#16]
What hot buttons are used to select text on one side only? (I don't know what the English word is. Here is an example in the picture)
I use wezterm/windows
![image](https://github.com/neurocyte/flow/assets/57330346/b7c0e307-5ffb-491f-b573-a54a221dbb7e)

**Comment by neurocyte** [comment]
To do a block selection first add cursors downwards with `Shift-Alt-Down` and then select sideways with `Shift-Right`. I hope that answers your question!

**Comment by zaeboba** [comment]
I'm sorry, but it doesn't work that way for me.

https://github.com/neurocyte/flow/assets/57330346/b6a6f1e7-b7a0-4126-8d36-cf2175f86ad6

**Comment by zaeboba** [comment]
hallo, in the version I have built at the moment, the keyboard shortcut does not work **Shift-Alt-Down**

**Comment by neurocyte** [comment]
> ps doesn't work in the original terminal, but it works in wezterm

Yes, as stated in the README.md, many keybindings require a terminal that supports kitty keyboard protocol. Most modern terminals do, but not all. Flow will print a message in the log if it detects kitty keyboard support. You can show the log on start with `flow --show-log`.

**Comment by zaeboba** [comment]
I don't know if that was a question?
here, the left one is the windows terminal "flow --show-log" opened immediately, the right one is westerm, it opened something incomprehensible 🤪
![image](https://github.com/user-attachments/assets/3a5d5f3f-8d14-4903-9a9a-cbb80ef3168f)

**Comment by neurocyte** [comment]
Ah, sorry, I completely over looked that you are on windows. kitty keyboard protocol is not a thing on windows. If Shift-Alt-up is not working it is because it is bound to some terminal command in Windows Terminal. Go into the setting and remove any conflicting bindings. I think they're in the Actions section.
