### ISSUE TITLE
high and lingering CPU use on each display refresh(?)

### ISSUE THREAD

**Issue by ilohmar** [neurocyte/flow#17]
Hi, really enjoying playing around (for now) with flow, but wondering about something.

This is on linux, in X and an alacritty terminal.  (Side note: alacritty seems to support all of flow's requirements and to work nicely AFAICT.)

I'm seeing high CPU usage starting with every cursor motion (no need for the viewport to scroll); in fact, a single <up> arrow press is enough to use one core.  The editor is still responsive (eg, I can hold-repeat arrow motions), but it takes 4..5s after the last keypress for CPU usage to go back to idle. The same thing even happens just switching to a different workspace or coming back.

This was on a zig file from the flow project itself, w/ zls running, but it occurs on plain text files w/o any LSP running just the same.

Is this expected or should I try and profile where the load happens?  It seems to be related to some very general kind of display-change refresh.

**Comment by neurocyte** [comment]
Flow should be idle within one or two frames of the last keypress. If not, there must be some background task that is still active. That is usually the LSP, but there are also a few other things the run async like change diffing. But, usually none of the background tasks should take more than a couple milliseconds unless you have hundereds of cursors.

How did you measure it? Was it a ReleaseFast build? Debug builds can be pretty slow.

You can run flow with tracing enabled to get a full picture of what is taking how long. Run flow with `-ttt` and upload the resulting `trace.log` file here and I should be able to tell exactly what it's doing. The trace file should be in the `~/.local/state/flow` directory on Linux.

**Comment by ilohmar** [comment]
Thanks for the info. It's a ReleaseFast build. So far, my "measurement" is just watching the CPU load indicator.  That's extremely imprecise, ofc, but the phenomenon is so obvious that the indicator is what caught my attention in the first place. Single-cursor use all the time.

Here is the trace, using a plain-text file without any language server involvement.  This is just startup, and pressing an arrow key once or twice:
[trace.log](https://github.com/user-attachments/files/16321249/trace.log)

**Comment by ilohmar** [comment]
Since I spotted some winch signal handling etc, I wanted to make sure that it's not due to alacritty creating some weirdness and tried the same thing in kitty.  The CPU load is less, but the few-s lingering load after a single arrow key remains: 
[trace.log](https://github.com/user-attachments/files/16321284/trace.log)

**Comment by neurocyte** [comment]
I can't reproduce the issue here at all. Are you on the latest version? Please pull and rebuild and see if you can still reproduce.

**Comment by ilohmar** [comment]
It was at the time I wrote, but I compiled a new version, anyway (zig 0.13.0).  I was not thinking about configuration yesterday, because I had forgotten I had changed it. Sorry for not checking that earlier, but with the default config all seems fine: it is `keystate_show` enabled that's causing the CPU load!

Can you reproduce that and is that ok?  If not, I have a hunch it is something about my environment (NOT using a desktop environment, but `i3wm` on X).

**Comment by neurocyte** [comment]
Ok. This is expected behavior then.

The keystate widget keeps the renderer running for a few seconds after every keystroke. It could be re-written to use timers, but it's really only a debugging tool so I'm fine with it as is.

If you want to see the full effect of the renderer constantly running you can also start Flow with `--no-sleep`. I use that occasionally for performance testing/measuring.
