### ISSUE TITLE
Language Request: Elixir

### ISSUE THREAD

**Issue by i-am-linja** [neurocyte/flow#24]
Elixir has great tooling: [`elixir-ls`](https://elixir-lsp.github.io/elixir-ls/), [`mix format`](https://hexdocs.pm/mix/main/Mix.Tasks.Format.html), and they even provide a [grammar](https://github.com/elixir-lang/tree-sitter-elixir).

**Comment by neurocyte** [comment]
Does `elixir-rs` need parameters? The command for `mix` should be `mix format -`. Is that correct?
