### ISSUE TITLE
[windows] recover terminal theme after quiting flow

### ISSUE THREAD

**Issue by lost22git** [neurocyte/flow#26]

**Comment by neurocyte** [comment]
We already reset the terminal theme on exit. Unfortunately the reset command is just ignored on windows.

The only solution I can see is to add an option that disables setting the terminal theme altogether. Either CLI or config.

**Comment by neurocyte** [comment]
It looks like the theme reset is broken everywhere. maybe it's not just a windows issue. I'll look into it.

**Comment by lost22git** [comment]
The problem still exists...(at least on Windows)

```
❯ git log -1
commit b831d99d1cb7c32489255be3872dce3503f1831c (HEAD -> master, origin/master, origin/HEAD)
Author: CJ van den Berg <cj@vdbonline.com>
Date:   Tue Aug 20 22:30:21 2024 +0200

    fix: remove set_terminal_style testing code

    closes #26

```

**Comment by neurocyte** [comment]
I will test on windows today. Which terminal are you using?

**Comment by lost22git** [comment]
Mainly windows terminal, but alacritty and wezterm have same issue.
