### ISSUE TITLE
command to exit with code > 0

### ISSUE THREAD

**Issue by ilohmar** [neurocyte/flow#27]
Many programs use external editors, eg, `git commit` will use `$EDITOR` to edit the commit message.  If the editor exits with non-zero exit code, this error aborts the commit operation.

While in this particular case, not saving the file is an alternative workflow (though *not* equivalent), in general, a "quit with some exit code > 0" command would be very helpful, especially given the terminal-centric nature of flow.

**Comment by neurocyte** [comment]
The command you are looking for is `force_terminate`. That will force flow to terminal (even with unsaved changes) with exit code 99.

**Comment by ilohmar** [comment]
Sorry for the noise.. I had seen the command, but messed up during my checking the exit code.
