### ISSUE TITLE
Proposal to add tab support when opening files

### ISSUE THREAD

**Issue by segfault-enjoyer** [neurocyte/flow#30]
What it says in the title. The biggest blocker for me at the moment is that the file picker is missing ability to just either press tab once and get auto completion or press tab twice and get a list of files.

**Comment by neurocyte** [comment]
A better file open command is a the top of the upcoming features list.

**Comment by segfault-enjoyer** [comment]
Noice. Should I close this as you're planning to work on it, leave it open or rename it to better fit your plans?

**Comment by neurocyte** [comment]
No, you can leave the issue as-is. It fits nicely already.
