### ISSUE TITLE
Improve/fix paste handling for multiline strings

### ISSUE THREAD

**Issue by zerebos** [neurocyte/flow#39]
I ran into this when trying to paste in a code snippet:

```lua
function Linemode:size_and_mtime()
	local year = os.date("%Y")
	local time = (self._file.cha.modified or 0) // 1

	if time > 0 and os.date("%Y", time) == year then
		time = os.date("%b %d %H:%M", time)
	else
		time = time and os.date("%b %d  %Y", time) or ""
	end

	local size = self._file:size()
	return ui.Line(string.format(" %s %s ", size and ya.readable_size(size) or "-", time))
end
```

This is how it ended up with flow
![image](https://github.com/user-attachments/assets/9bc5c3f5-3965-498e-988f-9338d6fc2271)

But if I use something like micro instead it works fine
![image](https://github.com/user-attachments/assets/0a6eeff4-5dc3-4dd9-9f12-240bbc1c3991)

I've tested this with Windows (WSL Ubuntu)/Windows Terminal and macOS/Ghostty and got the same results.

**Comment by neurocyte** [comment]
What exact method are you using to paste? Bracketed paste is supposed to prevent this behavior, but for some reason it seems not to be working. I'm certain ghostty supports bracketed paste and, I'm not entirely sure, but I think windows terminal does too.

**Comment by neurocyte** [comment]
Found it! It was the tab characters in the snippet you are pasting that caused my rudimentary paste sanitizer to bork and exit bracketed paste mode. Thus dumping the rest of the input as keystrokes.

I have added tabs to the list of allowed special chars in pastes.

**Comment by zerebos** [comment]
Figures that tabs would cause it, thanks for the fix!
