### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by VarLad** [neurocyte/flow#41]
I get this error after building latest commit of flow (bf3fe5f2bad97341bd7c1a9e6ed9d372358cf347), and running the binary

**Comment by VarLad** [comment]
Doesn't happen as of d3eb4e9913cf6ae2681f6a1060d39d7b7d83baf2
Method of building:

`./zig build -Doptimize=ReleaseFast`



Method of running:

`./zig-out/bin/flow`

**Comment by neurocyte** [comment]
That is very strange. Perhaps Zig is detecting your CPU capabilities incorrectly or something. Can you please try building with this command instead:

`./zig build -Doptimize=ReleaseFast -Dcpu=baseline`

That should tell zig to produce a generic works-on-any-cpu binary.

Alternatively, you can explicitly specify the target platform too:

`./zig build -Doptimize=ReleaseFast -Dcpu=baseline -Dtarget=x86_64-linux-musl`

**Comment by neurocyte** [comment]
I don't see how this can be a flow issue. I recommend you open an issue in the zig repo with your full system details.

**Comment by VarLad** [comment]
@neurocyte Building latest commit now just gives me:
`xz: (stdin): File format not recognized`

**Comment by VarLad** [comment]
Update: I shifted to distro's zig installation (instead of the zig fetch script in the repo) and everything works as intended for now.
Thanks for the help!

**Comment by neurocyte** [comment]
Ok, something must be wrong with the new posix zig wrapper. I will revert it just to be safe.
