### ISSUE TITLE
Missing syntax highlighting for C++?

### ISSUE THREAD

**Issue by zerebos** [neurocyte/flow#42]
Maybe this is something wonky on my end, but when using the `cpp` language the syntax highlighting seems to disappear mostly. Here's an example:

<img width="386" alt="image" src="https://github.com/user-attachments/assets/f681e77f-a2ec-483b-845d-22309be54a56">

but if I force the language to `c` (`--language=c`) it looks fine.

<img width="383" alt="image" src="https://github.com/user-attachments/assets/1186bb72-3351-41a9-a887-3bc39a51fd46">

But I should have the correct language server installed...

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/5f0deaed-ac5f-4530-a366-2d254b100b68">

is this something messed up on my end? I don't really remember this happening before.

**Comment by neurocyte** [comment]
This is not a problem on your end. There is some wierdness in the tree-sitter-cpp package's handling of syntax highlighting queries. The cpp highlighting is supposed to inherit from the c highlighting. (see https://github.com/tree-sitter/tree-sitter-cpp/blob/30f973c2244f0bff444186185f475c3bd76bc3a5/package.json#L64)

Flow doesn't have support for this just yet.

**Comment by neurocyte** [comment]
Fixed!

![image](https://github.com/user-attachments/assets/f363cca8-95e8-44c3-b96b-d7234a4f9c45)
