### ISSUE TITLE
Crashes on x86_64 mac

### ISSUE THREAD

**Issue by VisenDev** [neurocyte/flow#49]
Hardware: 2019 Macbook Pro
OS: macOS 13.2
ISA: x86_64
Terminal: Ghostty master

Steps to replicate

<img width="1263" alt="Screenshot 2024-10-18 at 1 27 15 PM" src="https://github.com/user-attachments/assets/b01e0703-7e40-410a-97ae-d4d35a72319c">

Then run `./zig-out/bin/flow src/tui/tui.zig`

The program then crashes and breaks my terminal

<img width="1680" alt="Screenshot 2024-10-18 at 1 27 32 PM" src="https://github.com/user-attachments/assets/1b07b148-698a-42db-b267-1f61f37c6a9a">

I attempted to debug this in lldb, but the zig stack probe function is segfaulting. 

<img width="970" alt="Screenshot 2024-10-18 at 1 34 17 PM" src="https://github.com/user-attachments/assets/6be6652d-0a5a-4c25-a388-bb22e8cf27d8">

I've seen this happen before doing certain types of json parsing (see https://github.com/ziglang/zig/issues/17195). So I tried deleting `~/.config/flow/config.json`

Doing this fixes the segfault, but the program then crashes for another reason. (I believe it has to do with conflicts over capturing the tty). Because of this, I can't get good details on why exactly the original crash happens

<img width="1016" alt="Screenshot 2024-10-18 at 1 35 07 PM" src="https://github.com/user-attachments/assets/6d156f6f-50e3-41c1-85e6-7c2e7b64ff7f">

The program also crashes in other optimize mods, but for other reasons. `ReleaseFast` seems to crash due to a segmentation fault

**Comment by VisenDev** [comment]
With more testing, I have discovered that flow will not immediately crash if I start it without an initial file argument. However it does crash as soon as I attempt to open `src/tui/tui.zig` - Perhaps there is a LSP related issue?

**Comment by VisenDev** [comment]
This issue seems related https://github.com/neurocyte/flow/issues/41

Following on from that issue - I have now tried running the command using the `zig` wrapper script, but that does not seem to work.

<img width="998" alt="Screenshot 2024-10-18 at 1 48 03 PM" src="https://github.com/user-attachments/assets/c28c4ca4-90bf-476f-8f3d-2a9dda090f81">

**Comment by neurocyte** [comment]
> but now the editor won't quit no matter which mode I am in or which way I try to quit.... hmm.....

It sounds like something may have hung internally. Did you try quitting with the `Force quit without saving` command? That should always work.

If you can reproduce a situation where flow refuses to exit, please run flow with `flow -t 5` and submit the `trace.log` of the flow session that hung.

**Comment by neurocyte** [comment]
I've added a note about cpu=baseline to the readme.

**Comment by VisenDev** [comment]
I wasn't able to reproduce the failure to quit, however I am still getting segmentation faults - possibly zls related

Flow git was updated to latest master and built with `zig build -Doptimize=ReleaseFast -Dcpu=baseline`

[trace.log of crash](https://github.com/user-attachments/files/17447935/trace.log)


<img width="1680" alt="Screenshot 2024-10-19 at 8 08 07 PM" src="https://github.com/user-attachments/assets/a09c7633-c3f8-4b8d-8fce-77c3369b1fea">

**Comment by neurocyte** [comment]
For regular crashes I need a back trace.

**Comment by neurocyte** [comment]
Anothet thought. Perhaps `-Dcpu=baseline` is not enough to stop zig from mis-detecting your cpu. Please try building with the full target like when cross compiling. See cross compilation in `README.md`.

**Comment by VisenDev** [comment]
> Anothet thought. Perhaps `-Dcpu=baseline` is not enough to stop zig from mis-detecting your cpu. Please try building with the full target like when cross compiling. See cross compilation in `README.md`.

This has not fixed the crashes unfortunately

> For regular crashes I need a back trace.

Could you elaborate on how to produce this? I assume you mean a lldb/gdb backtrace? As I stated in my original issue, I haven't been able to figure out how to produce one of those because the program won't start inside of lldb due to `SIGTTOU`

**Comment by neurocyte** [comment]
Run flow with `flow --debug-wait` and attach to it from another terminal with gdb or lldb. Then start flow with a keypress when the debugger is attached and continued.

**Comment by neurocyte** [comment]
This should be fixed with 048ea5f086550bcdf8e4eca3794e60c384a5b814
