### ISSUE TITLE
diagnostics sometimes wrap and block text

### ISSUE THREAD

**Issue by xdBronch** [neurocyte/flow#51]
im not entirely sure in what cases this happens, only noticed it with rust so far. seems to be when there are multiple diagnostics in the same place and/or when a diagnostic has multiple lines
![image](https://github.com/user-attachments/assets/bde57a63-2079-4361-a81f-cc9eaaa0a97f)

**Comment by neurocyte** [comment]
Looks like flow doesn't render multi-line diagnostics properly.
