### ISSUE TITLE
F5 inspector view on tab-indented line displays info of wrong position

### ISSUE THREAD

**Issue by ingolohmar** [neurocyte/flow#54]
When I'm in a go file (indented with tabs), the tree-sitter debug view seems to consistently display info of a token at a wrongly calculated position, namely in the same line, but mixing up character and visual columns.

Ie, with two indentation tabs of size 4, and if I'm at *visual* column 10 (4 * 2 tabs + 2 more chars), it would display info of the *character* column 10 (2 tab chars + 8 more chars) which is too far into the line.

I hope this is understandable. :)

**Comment by neurocyte** [comment]
It's called the inspector view, but yes, you are correct. There is an alignment issue there somewhere.

**Comment by ingolohmar** [comment]
That's awesome, thank you!
