### ISSUE TITLE
Command to quickly jump between recently opened files

### ISSUE THREAD

**Issue by VisenDev** [neurocyte/flow#56]
I often want to quickly move between a couple files. While the recent files menu works file for this, it would be nice if there was a command to directly cycle thru your recent file list (Similar to how the jump list works).

Alternatively, a command that simply jumps to your *most recently* opened file would also accomplish this purpose.

**Comment by neurocyte** [comment]
To be clear. `Ctrl-e Ctrl-e` should immediatly jump to the most recently used file when you let go of the `Ctrl` key. If not, you don't have good keybinding support in your terminal.

**Comment by VisenDev** [comment]
> How is what you're describing different to `Ctrl-e Ctrl-e` (double tap)?

This accomplishes the same thing, but it requires multiple key presses. Ideally I'd like to be able to remap this functionality with a quicker keybinding - hence a dedicated command would make this easier

**Comment by neurocyte** [comment]
Do you have a preference for the keybinding?

**Comment by VisenDev** [comment]
gg

> Do you have a preference for the keybinding?

No preference beyond it being quick and ergonomic

If we get the keybindings pr working it should be fairly easy to add support for user customizable keybindings, so the default won't be as important.

**Comment by neurocyte** [comment]
Bound to C-^ like nvim's default
