### ISSUE TITLE
Setting to format on save

### ISSUE THREAD

**Issue by VisenDev** [neurocyte/flow#58]

**Comment by xdBronch** [comment]
https://github.com/neurocyte/flow/blob/0dc6fae7b74b554d905d3cd2524bfd00f346f4f3/src/config.zig#L19
thats already a thing though?

**Comment by VisenDev** [comment]
> https://github.com/neurocyte/flow/blob/0dc6fae7b74b554d905d3cd2524bfd00f346f4f3/src/config.zig#L19
> 
> 
> thats already a thing though?

Whoops didn't notice that, thanks
