### ISSUE TITLE
Multiline cursor support

### ISSUE THREAD

**Issue by VisenDev** [neurocyte/flow#59]
I'm not sure if flow does not have this feature or I have not figured out how to use it. But either way, I have been missing multiline cursors when working on PR #57 in flow

**Comment by neurocyte** [comment]
What is a multiline cursor?

**Comment by VisenDev** [comment]
> Flow has extensive multi cursor editing support if that is what you mean.

Okay awesome

**Comment by nurpax** [comment]
Hi, I also see that flow has multiline cursor but I don't know how to trigger this feature. Any tips where to start?

I did find `ctrl-d` which does the same as in VSCode (searches for word and creates a cursor at each occurrence.)

But I don't know how to f.ex. select multiple lines into a multicursor.  This would be `ctrl-alt-<up/down arrow>` in VSCode and many other editors.

**Comment by neurocyte** [comment]
> But I don't know how to f.ex. select multiple lines into a multicursor. This would be ctrl-alt-\u003Cup/down arrow> in VSCode and many other editors.

Yes, these keys are the same in flow. You can search for commands and see their keybindings with ctrl+f2. Search there for `add cursor`.

**Comment by neurocyte** [comment]
`alt+shift+up`/`+down` is usually bound to 'Resize pane up/down' in Windows Terminal. Remove these bindings in Windows Terminal's settings (or re-bind them) and it should work.
