### ISSUE TITLE
Language Request: Add support for Julia language 

### ISSUE THREAD

**Issue by VarLad** [neurocyte/flow#61]
It'd be nice if Flow could support LS and highlighting via tree-sitter for Julia Language as well.

**Comment by neurocyte** [comment]
Yes, julia apparently compiles the language server the first time you run it. This took around 35 seconds on my machine.

I have added a configuration option `lsp_request_timeout` to set the language server timeout. It defaults to 10 seconds, so you'll need to increase it for the julia lsp.
