### ISSUE TITLE
Feature Request: Racket support

### ISSUE THREAD

**Issue by VisenDev** [neurocyte/flow#66]
Syntax highlighting for racket (and other schemes) would be nice.

**Comment by neurocyte** [comment]
Some parsers to choose from:

https://github.com/6cdh/tree-sitter-racket
https://github.com/Wilfred/tree-sitter-elisp
https://github.com/sogaiu/tree-sitter-clojure

**Comment by neurocyte** [comment]
Do you have any preference?

**Comment by VisenDev** [comment]
> Do you have any preference?

Not really

**Comment by neurocyte** [comment]
Flow already supports scheme via https://github.com/6cdh/tree-sitter-scheme

**Comment by VarLad** [comment]
Hello! Any idea if this can be reopened for include LSP support? 😅 
https://codeberg.org/rgherdt/scheme-lsp-server seems nice

**Comment by neurocyte** [comment]
> Any idea if this can be reopened for include LSP support?

It should work fine.

You can test it by adding it a line to `src/syntax/src/file_types.zig` in the scheme section like this:

```
    .language_server = .{"guile-lsp-server},
```

And then rebuild flow.

If it works ok report back here and I'll add it to the default build. I would do it myself, but I don't have any scheme development environment setup.
