### ISSUE TITLE
Possible bug: Editor does not accept back slashes

### ISSUE THREAD

**Issue by n4skx** [neurocyte/flow#72]
I'm currently under Windows 11, using WezTerm and flow. I'm unable to insert backslashes into the editor.
### Info
```
> flow -v
Flow Control: a programmer's text editor

version: 47dd41b
branch: master at https://github.com/neurocyte/flow
```

```
> wezterm.exe -V
wezterm 20240203-110809-5046fc22
```
### Reproduce
1. Open any file with flow
2. Type backslash character (\\)

**Comment by neurocyte** [comment]
I cannot reproduce this here. Same build of flow and wezterm on win11 works fine for me. Is it perhaps a wezterm configuration issue on your end?  See if it's reproducable it with `wezterm --skip-config`. Otherwise perhaps it's a windows keyboard layout issue?

I really don't see how this can be flow's fault, so I'll close for now. Feel free to re-open if you can provide more specifics on how to reproduce.

**Comment by n4skx** [comment]
Doesn't seems like a issue around wezterm configuration, my configuration is very simple, and doesn't contains any keybindings or something like that. Tried with `wezterm --skip-config` didn't work.

My config wezterm config is:
```lua
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.max_fps = 120
config.animation_fps = 120
config.front_end = 'WebGpu'
config.color_scheme = 'Ef-Elea-Dark'
config.default_prog = { 'powershell' }

config.webgpu_power_preference = 'HighPerformance'
config.webgpu_preferred_adapter = {
    backend = 'Vulkan',
    device = 9698,
    device_type = 'DiscreteGpu',
    driver = 'NVIDIA',
    driver_info = '555.99',
    name = 'NVIDIA GeForce RTX 3050 Laptop GPU',
    vendor = 4318,
}

config.window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
}

config.window_frame = {
    font = wezterm.font { family = 'Roboto', weight = 'Bold' },
    font_size = 12.0,

    active_titlebar_bg = '#333333',
    inactive_titlebar_bg = '#333333',
}

config.colors = {
    tab_bar = {
        inactive_tab_edge = '#575757',
    },
}

return config
```

My keyboard layouts are:
![image](https://github.com/user-attachments/assets/b5e50b3c-4a56-46a4-b067-fe083474521a)

I can insert backslashes on wezterm, but not on flow, i also tried to enable raw inputs but didn't worked as well.

**Comment by neurocyte** [comment]
Please start flow with `flow --show-input` at see if the backslash key generates any events at all. If it does, please paste them here.

**Comment by n4skx** [comment]
It doesn't generate any events when pressing backslashes

**Comment by neurocyte** [comment]
Sorry, then it is definitely a wezterm bug, not flow. Please report it there.

**Comment by n4skx** [comment]
Also tried with Windows Terminals (wt) and standard command prompt, backslashes doesn't work with them as well

**Comment by neurocyte** [comment]
I think it's a missing key mapping in libvaxis.

**Comment by neurocyte** [comment]
See if this fixes it for you. Thanks for the bug report!

**Comment by n4skx** [comment]
Working just fine! Thank you so much!
