### ISSUE TITLE
CommandNotFound: save_selection

### ISSUE THREAD

**Issue by Satheeshsk369** [neurocyte/flow#76]
when i try to save a file, it shows this error in helix mode

**Comment by neurocyte** [comment]
The command `save_selection` does not exist yet.

Helix mode is still very much a work-in-progress and many of the commands referenced in the bindings do not actually exist yet. They are expected to have Helix mode specific implementations and will be added when the Helix mode users get around to them. If you want to see it completed, I highly recommend you join the discord and post about your issues in the helix-mode channel there.

Alternatively you can rebind commands as you see fit with the `Edit keybindings` command. See a list of commands (that actually exist) that you can bind with the `Insert command name` command (usually bound to `ctrl+f2`). Save the bindings file and restart Flow Control for your changes to take effect.

**Comment by neurocyte** [comment]
Ok, I've checked the helix docs and flow's binding is correct.

`Ctrl-s` is `save_selection` which should store the current selection in the jump history. I'll add that.

`save_file` in helix should be `:w`.
