### ISSUE TITLE
Unable to type tilde

### ISSUE THREAD

**Issue by edwloef** [neurocyte/flow#78]
On a German (QWERTZ) keyboard layout, you press AltGr + "+" to type \~. Using `flow --show-input`, this is shown as "~", but when in the editor or opening a file a "+" comes out. I'm using ghostty, if that's relevant, but since show-input gives the correct output I assume it isn't.

This issue extends to all characters typed via AltGr.

Additionally, the file open dialog seems to insert extra spaces for non-ascii characters such as ß.

![image](https://github.com/user-attachments/assets/832912fe-eb32-420d-a447-c6ce62cf308c)

**Comment by VisenDev** [comment]
This might be a libvaxis keyboard input problem. I'm not sure

**Comment by edwloef** [comment]
Trying the libvaxis text_input demo seems to work fine.

**Comment by neurocyte** [comment]
I reported it here: https://github.com/ghostty-org/ghostty/issues/2981

**Comment by neurocyte** [comment]
I will close this here as I don't think there is anything flow can do to fix it. It works fine in kitty and foot.

**Comment by neurocyte** [comment]
It looks to me that this is also a problem with flow's new dynamic keybinding system, so I have reopened.

If there is a flow fix, it may solve the issue independently of the ghostty issue.
