### ISSUE TITLE
Highlighting text and deleting it with "backspace" deletes extra characters

### ISSUE THREAD

**Issue by edwloef** [neurocyte/flow#83]
If the next character after the selection is a newline, it deletes an extra newline. If it is a segment of text, that is deleted.

**Comment by edwloef** [comment]
Correction: it doesn't always seem to be the amount of extra characters I initially encountered and described above.

**Comment by neurocyte** [comment]
I can't reproduce this behaviour. Do you have a specific file that can trigger it?

Or maybe I just don't understand what you mean. Could you please describe the exact steps to you're using.

**Comment by edwloef** [comment]
https://github.com/user-attachments/assets/6e4f8987-c7d6-4130-93f0-fc6e3df8c4ab

Here's a video highlighting what I encountered, within flow's PKGBUILD. I'm only selecting text and pressing backspace here.

**Comment by neurocyte** [comment]
Ok, it's specifically the tab character on a blank line (line 27) that is causing it. Wierd bug! Thanks for reporting it.
