### ISSUE TITLE
Background color is not reset after exiting flow 

### ISSUE THREAD

**Issue by nurpax** [neurocyte/flow#94]
This sequence of operations leaves the flow background color in my shell after exiting flow:

1. Start a new tab in Windows terminal
2. SSH into a Linux machine, start flow.  Flow sets the background color to gray.
3. Exit flow.  Background is still gray and not black as it was originally.

The Linux machine I ssh'd into is running Ubuntu 22.

![image](https://github.com/user-attachments/assets/fcfab194-ab21-422f-883d-5a7bb104aa61)

![image](https://github.com/user-attachments/assets/f1f8d1d8-6d48-4cfa-b92a-b70dc361e795)

![image](https://github.com/user-attachments/assets/489d424e-cf5f-46e7-92c3-b526a91ec50b)

**Comment by neurocyte** [comment]
Yes, unfortunately Windows Terminal does not support resetting the terminal color scheme. Set `enable_terminal_color_scheme` to `false` in your flow config to disable this feature of flow.
